"""Postgres-backed WebUI session store.

Implements the canonical ``api.session_store.SessionStore`` contract against
PostgreSQL, proving the abstraction is not coupled to the embedded SQLite
backend (or the filesystem): same sessions/messages/tool_calls/
context_messages/anchor_scenes model, ``extra_json`` as JSONB, a meta table
for the revision counter and cutover markers, and the same stale-writer
fenced upsert.

Not wired into production config yet — used by the backend contract tests
(tests/test_session_store_contract.py) and as the reference for future
network backends.
"""
from __future__ import annotations

import json
import threading
import time
from typing import Any

from api.webui_session_sqlite import (
    _ALWAYS_PRESENT_FIELDS,  # noqa: F401  (contract parity reference)
    _SESSION_BOOL_FIELDS,
    _SESSION_JSON_FIELDS,
    _SESSION_SCALAR_FIELDS,
    StaleSessionWriteError,
    _is_safe_session_id,
    _json_dump,
)

_SCHEMA_SQL = """
CREATE TABLE IF NOT EXISTS sessions (
    session_id TEXT PRIMARY KEY,
    title TEXT,
    workspace TEXT,
    model TEXT,
    model_provider TEXT,
    model_explicit_pick_signature TEXT,
    created_at DOUBLE PRECISION,
    updated_at DOUBLE PRECISION,
    pinned INTEGER NOT NULL DEFAULT 0,
    archived INTEGER NOT NULL DEFAULT 0,
    project_id TEXT,
    profile TEXT,
    input_tokens INTEGER DEFAULT 0,
    output_tokens INTEGER DEFAULT 0,
    estimated_cost DOUBLE PRECISION DEFAULT 0,
    cache_read_tokens INTEGER DEFAULT 0,
    cache_write_tokens INTEGER DEFAULT 0,
    personality TEXT,
    active_stream_id TEXT,
    pending_user_message TEXT,
    pending_started_at DOUBLE PRECISION,
    pending_user_source TEXT,
    pending_attachments TEXT,
    compression_anchor_visible_idx INTEGER,
    compression_anchor_message_key TEXT,
    compression_anchor_summary TEXT,
    pre_compression_snapshot INTEGER DEFAULT 0,
    context_engine TEXT,
    compression_anchor_engine TEXT,
    compression_anchor_mode TEXT,
    compression_anchor_details TEXT,
    context_engine_state TEXT,
    context_length INTEGER,
    threshold_tokens INTEGER,
    last_prompt_tokens INTEGER,
    post_compression_context_tokens_estimate INTEGER,
    compression_recovery TEXT,
    recommended_recovery_action TEXT,
    compression_recovery_source_session_id TEXT,
    compression_recovery_action TEXT,
    truncation_watermark DOUBLE PRECISION,
    truncation_boundary DOUBLE PRECISION,
    gateway_routing TEXT,
    gateway_routing_history TEXT,
    llm_title_generated INTEGER DEFAULT 0,
    manual_title INTEGER DEFAULT 0,
    clear_generation TEXT,
    parent_session_id TEXT,
    worktree_path TEXT,
    worktree_branch TEXT,
    worktree_repo_root TEXT,
    worktree_created_at DOUBLE PRECISION,
    is_cli_session INTEGER DEFAULT 0,
    source_tag TEXT,
    raw_source TEXT,
    session_source TEXT,
    source_label TEXT,
    read_only INTEGER DEFAULT 0,
    enabled_toolsets TEXT,
    composer_draft TEXT,
    process_wakeup_pause TEXT,
    share_token TEXT,
    share_created_at DOUBLE PRECISION,
    message_count INTEGER DEFAULT 0,
    anchor_scene_index TEXT,
    anchor_scene_index_hash TEXT,
    anchor_activity_scenes_json TEXT,
    created_workspace TEXT,
    intentional_shrink_generation TEXT,
    user_id TEXT,
    chat_id TEXT,
    session_key TEXT,
    platform TEXT,
    extra_json TEXT,
    generation INTEGER NOT NULL DEFAULT 0,
    null_fields_json TEXT
);

CREATE TABLE IF NOT EXISTS messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id TEXT NOT NULL REFERENCES sessions(session_id) ON DELETE CASCADE,
    idx INTEGER NOT NULL,
    message_json TEXT NOT NULL,
    UNIQUE(session_id, idx)
);
CREATE INDEX IF NOT EXISTS idx_messages_session ON messages(session_id, idx);

CREATE TABLE IF NOT EXISTS tool_calls (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id TEXT NOT NULL REFERENCES sessions(session_id) ON DELETE CASCADE,
    idx INTEGER NOT NULL,
    tool_call_json TEXT NOT NULL,
    UNIQUE(session_id, idx)
);
CREATE INDEX IF NOT EXISTS idx_tool_calls_session ON tool_calls(session_id, idx);

CREATE TABLE IF NOT EXISTS context_messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id TEXT NOT NULL REFERENCES sessions(session_id) ON DELETE CASCADE,
    idx INTEGER NOT NULL,
    message_json TEXT NOT NULL,
    UNIQUE(session_id, idx)
);
CREATE INDEX IF NOT EXISTS idx_context_messages_session ON context_messages(session_id, idx);

CREATE TABLE IF NOT EXISTS anchor_scenes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    scene_hash TEXT NOT NULL,
    session_id TEXT NOT NULL REFERENCES sessions(session_id) ON DELETE CASCADE,
    scene_json TEXT NOT NULL,
    UNIQUE(scene_hash, session_id)
);

CREATE TABLE IF NOT EXISTS meta (
    key TEXT PRIMARY KEY,
    value TEXT
);
"""


class WebUIPostgresSessionDB:
    """SessionStore implementation backed by PostgreSQL."""

    def __init__(self, dsn: str):
        import psycopg

        self._dsn = dsn
        self._psycopg = psycopg
        self._local = threading.local()
        self._ensure_schema()

    def _conn(self):
        conn = getattr(self._local, "conn", None)
        if conn is None or conn.closed:
            conn = self._psycopg.connect(self._dsn, autocommit=False)
            self._local.conn = conn
        return conn

    def _ensure_schema(self) -> None:
        conn = self._conn()
        with conn:
            for stmt in _SCHEMA_SQL.split(";"):
                stmt = stmt.strip()
                if stmt:
                    conn.execute(stmt)
            # v4 columns for databases created by earlier versions.
            conn.execute(
                "ALTER TABLE sessions ADD COLUMN IF NOT EXISTS generation INTEGER NOT NULL DEFAULT 0"
            )
            conn.execute(
                "ALTER TABLE sessions ADD COLUMN IF NOT EXISTS null_fields_json TEXT"
            )
            if conn.execute("SELECT 1 FROM meta WHERE key = 'created_by'").fetchone() is None:
                has_rows = conn.execute("SELECT 1 FROM sessions LIMIT 1").fetchone() is not None
                conn.execute(
                    "INSERT INTO meta (key, value) VALUES ('created_by', %s)",
                    ("legacy" if has_rows else "app",),
                )

    def close(self) -> None:
        conn = getattr(self._local, "conn", None)
        if conn is not None and not conn.closed:
            conn.close()
        self._local.conn = None

    # -- meta / revision / cutover ----------------------------------------

    def _bump_revision(self, conn) -> None:
        conn.execute(
            "INSERT INTO meta (key, value) VALUES ('revision', '1') "
            "ON CONFLICT(key) DO UPDATE SET value = CAST(CAST(meta.value AS INTEGER) + 1 AS TEXT)"
        )

    def get_revision(self) -> int:
        try:
            row = self._conn().execute(
                "SELECT value FROM meta WHERE key = 'revision'"
            ).fetchone()
            return int(row[0]) if row is not None else 0
        except Exception:
            return int(time.time_ns())

    def set_meta(self, key: str, value: str) -> None:
        conn = self._conn()
        with conn:
            conn.execute(
                "INSERT INTO meta (key, value) VALUES (%s, %s) "
                "ON CONFLICT(key) DO UPDATE SET value = excluded.value",
                (key, value),
            )

    def get_meta(self, key: str) -> str | None:
        try:
            row = self._conn().execute(
                "SELECT value FROM meta WHERE key = %s", (key,)
            ).fetchone()
            return row[0] if row is not None else None
        except Exception:
            return None

    def is_active(self) -> bool:
        try:
            rows = self._conn().execute("SELECT key, value FROM meta").fetchall()
            meta = {row[0]: row[1] for row in rows}
        except Exception:
            return True
        if meta.get("created_by") == "migration" and meta.get("migration_complete") != "1":
            return False
        return True

    # -- reads -------------------------------------------------------------

    def list_sessions(self) -> list[dict[str, Any]]:
        cur = self._conn().execute(
            "SELECT * FROM sessions ORDER BY pinned DESC, updated_at DESC, created_at DESC"
        )
        cols = [c.name for c in cur.description]
        return [self._row_to_metadata(dict(zip(cols, row))) for row in cur.fetchall()]

    def session_exists(self, sid: str) -> bool:
        if not _is_safe_session_id(sid):
            return False
        row = self._conn().execute(
            "SELECT 1 FROM sessions WHERE session_id = %s", (sid,)
        ).fetchone()
        return row is not None

    def _fetch_row(self, sid: str) -> dict[str, Any] | None:
        cur = self._conn().execute(
            "SELECT * FROM sessions WHERE session_id = %s", (sid,)
        )
        row = cur.fetchone()
        if row is None:
            return None
        cols = [c.name for c in cur.description]
        return dict(zip(cols, row))

    def read_session(self, sid: str) -> dict[str, Any] | None:
        if not _is_safe_session_id(sid):
            return None
        d = self._fetch_row(sid)
        if d is None:
            return None
        session = self._row_to_session(d)
        session["messages"] = self._read_json_table("messages", "message_json", sid)
        session["tool_calls"] = self._read_json_table("tool_calls", "tool_call_json", sid)
        session["context_messages"] = self._read_json_table("context_messages", "message_json", sid)
        return session

    def read_metadata_only(self, sid: str) -> dict[str, Any] | None:
        if not _is_safe_session_id(sid):
            return None
        d = self._fetch_row(sid)
        if d is None:
            return None
        return self._row_to_metadata(d, include_computed=False)

    def _read_json_table(self, table: str, column: str, sid: str) -> list[dict[str, Any]]:
        cur = self._conn().execute(
            f"SELECT {column} FROM {table} WHERE session_id = %s ORDER BY idx", (sid,)
        )
        return [json.loads(row[0]) for row in cur.fetchall()]

    # -- writes ------------------------------------------------------------

    def write_session(
        self,
        session: dict[str, Any],
        *,
        expected_generation: int | None = None,
        force: bool = False,
    ) -> dict[str, Any]:
        if not isinstance(session, dict):
            raise TypeError("session must be a dict")
        sid = session.get("session_id")
        if not _is_safe_session_id(sid):
            raise ValueError(f"Unsafe session_id {sid!r}")

        import copy

        payload = copy.deepcopy(session)
        messages = payload.pop("messages", [])
        tool_calls = payload.pop("tool_calls", [])
        context_messages = payload.pop("context_messages", [])
        if "message_count" not in payload:
            payload["message_count"] = len(messages)

        conn = self._conn()
        with conn:
            self._bump_revision(conn)
            self._write_session_row(
                conn, sid, payload,
                expected_generation=expected_generation, force=force,
            )
            self._write_json_table(conn, "messages", "message_json", sid, messages)
            self._write_json_table(conn, "tool_calls", "tool_call_json", sid, tool_calls)
            self._write_json_table(conn, "context_messages", "message_json", sid, context_messages)
            self._write_anchor_scenes(conn, sid, payload.get("anchor_activity_scenes", {}))
        return self.read_session(sid) or {}

    def _write_session_row(
        self,
        conn,
        sid: str,
        payload: dict[str, Any],
        *,
        expected_generation: int | None = None,
        force: bool = False,
    ) -> None:
        cols = ["session_id"]
        vals: list[Any] = [sid]
        for field in _SESSION_SCALAR_FIELDS:
            if field == "anchor_scene_index_hash":
                continue
            cols.append(field)
            v = payload.get(field)
            if v is None and field in _SESSION_BOOL_FIELDS:
                vals.append(0)
            elif v is None:
                vals.append(None)
            elif field in _SESSION_JSON_FIELDS:
                vals.append(_json_dump(v))
            elif field in _SESSION_BOOL_FIELDS:
                vals.append(1 if v else 0)
            else:
                vals.append(v)
        cols.append("anchor_scene_index_hash")
        idx = payload.get("anchor_scene_index")
        vals.append(_json_dump(idx) if isinstance(idx, dict) else None)
        cols.append("anchor_activity_scenes_json")
        scenes = payload.get("anchor_activity_scenes")
        vals.append(_json_dump(scenes) if scenes is not None else None)
        consumed = set(_SESSION_SCALAR_FIELDS) | {"session_id", "anchor_activity_scenes"}
        extra = {k: v for k, v in payload.items() if k not in consumed}
        cols.append("extra_json")
        vals.append(_json_dump(extra) if extra else None)
        # Key-presence contract: explicitly-None keys read back as present None.
        null_fields = sorted(k for k, v in payload.items() if v is None)
        cols.append("null_fields_json")
        vals.append(_json_dump(null_fields) if null_fields else None)

        row = conn.execute(
            "SELECT generation FROM sessions WHERE session_id = %s", (sid,)
        ).fetchone()
        current_generation = int(row[0] or 0) if row is not None else None
        if current_generation is None:
            new_generation = 1
        elif force:
            new_generation = current_generation + 1
        elif expected_generation is None or int(expected_generation) != current_generation:
            raise StaleSessionWriteError(
                f"Refusing to overwrite session {sid!r}: expected generation "
                f"{expected_generation!r} != persisted {current_generation!r} "
                f"(stale writer or unloaded lineage; use force only for "
                f"deliberate heals)"
            )
        else:
            new_generation = current_generation + 1

        cols.append("generation")
        vals.append(new_generation)

        placeholders = ", ".join("%s" for _ in cols)
        conn.execute(
            f"INSERT INTO sessions ({', '.join(cols)}) VALUES ({placeholders}) "
            "ON CONFLICT(session_id) DO UPDATE SET "
            + ", ".join(f"{c}=excluded.{c}" for c in cols),
            vals,
        )

    def _write_json_table(self, conn, table: str, column: str, sid: str, rows: list[Any]) -> None:
        conn.execute(f"DELETE FROM {table} WHERE session_id = %s", (sid,))
        for idx, row in enumerate(rows):
            if not isinstance(row, dict):
                continue
            conn.execute(
                f"INSERT INTO {table} (session_id, idx, {column}) VALUES (%s, %s, %s)",
                (sid, idx, _json_dump(row)),
            )

    def _write_anchor_scenes(self, conn, sid: str, scenes: Any) -> None:
        conn.execute("DELETE FROM anchor_scenes WHERE session_id = %s", (sid,))
        if not isinstance(scenes, dict):
            return
        for hsh, scene in scenes.items():
            conn.execute(
                "INSERT INTO anchor_scenes (scene_hash, session_id, scene_json) VALUES (%s, %s, %s)",
                (hsh, sid, _json_dump(scene)),
            )

    def update_metadata(self, sid: str, fields: dict[str, Any]) -> dict[str, Any]:
        if not isinstance(fields, dict):
            raise TypeError("fields must be a dict")
        unsafe = set(fields) & {"session_id", "messages", "tool_calls", "message_count"}
        if unsafe:
            raise ValueError(f"Unsafe session metadata fields: {', '.join(sorted(unsafe))}")

        conn = self._conn()
        with conn:
            self._bump_revision(conn)
            set_parts: list[str] = []
            values: list[Any] = []
            extras: dict[str, Any] = {}
            for k, v in fields.items():
                if k in _SESSION_JSON_FIELDS:
                    set_parts.append(f"{k} = %s")
                    values.append(None if v is None else _json_dump(v))
                elif k in _SESSION_SCALAR_FIELDS:
                    set_parts.append(f"{k} = %s")
                    values.append(v)
                else:
                    extras[k] = v
            # Maintain null key-presence across targeted updates.
            row = conn.execute(
                "SELECT null_fields_json FROM sessions WHERE session_id = %s", (sid,)
            ).fetchone()
            null_fields: list[str] = []
            if row is not None and row[0]:
                try:
                    parsed = json.loads(row[0])
                    if isinstance(parsed, list):
                        null_fields = [x for x in parsed if isinstance(x, str)]
                except (json.JSONDecodeError, TypeError):
                    pass
            for k, v in fields.items():
                if v is None:
                    if k not in null_fields:
                        null_fields.append(k)
                elif k in null_fields:
                    null_fields.remove(k)
            set_parts.append("null_fields_json = %s")
            values.append(_json_dump(null_fields) if null_fields else None)
            if extras:
                row = conn.execute(
                    "SELECT extra_json FROM sessions WHERE session_id = %s", (sid,)
                ).fetchone()
                current: dict[str, Any] = {}
                if row is not None and row[0]:
                    try:
                        parsed = json.loads(row[0])
                        if isinstance(parsed, dict):
                            current = parsed
                    except (json.JSONDecodeError, TypeError):
                        pass
                current.update(extras)
                set_parts.append("extra_json = %s")
                values.append(_json_dump(current))
            # updated_at rides in fields and is a scalar column, so the loop
            # above already covers it; Postgres rejects duplicate assignments.
            values.append(sid)
            conn.execute(
                f"UPDATE sessions SET {', '.join(set_parts)} WHERE session_id = %s",
                values,
            )
        return self.read_metadata_only(sid) or {}

    def delete_session(self, sid: str) -> bool:
        if not _is_safe_session_id(sid):
            return False
        conn = self._conn()
        with conn:
            self._bump_revision(conn)
            cur = conn.execute("DELETE FROM sessions WHERE session_id = %s", (sid,))
            conn.execute("DELETE FROM messages WHERE session_id = %s", (sid,))
            conn.execute("DELETE FROM tool_calls WHERE session_id = %s", (sid,))
            conn.execute("DELETE FROM context_messages WHERE session_id = %s", (sid,))
            conn.execute("DELETE FROM anchor_scenes WHERE session_id = %s", (sid,))
        return cur.rowcount > 0

    def archive(self, sid: str, archived: bool = True) -> dict[str, Any]:
        return self.update_metadata(sid, {"archived": 1 if archived else 0})

    # -- row mapping (mirrors the SQLite store) ----------------------------

    def _row_to_metadata(self, d: dict[str, Any], *, include_computed: bool = True) -> dict[str, Any]:
        row: dict[str, Any] = {"session_id": d["session_id"]}
        for field in _SESSION_SCALAR_FIELDS:
            if field == "anchor_scene_index_hash":
                continue
            v = d.get(field)
            if v is None and field not in _ALWAYS_PRESENT_FIELDS:
                continue
            if field in _SESSION_JSON_FIELDS and isinstance(v, str):
                v = json.loads(v)
            elif field in _SESSION_BOOL_FIELDS and v is not None:
                v = bool(v)
            row[field] = v
        if include_computed:
            row["last_message_at"] = d.get("updated_at") or d.get("created_at")
        extra_json = d.get("extra_json")
        if extra_json:
            try:
                extra = json.loads(extra_json)
            except (json.JSONDecodeError, TypeError):
                extra = None
            if isinstance(extra, dict):
                for k, v in extra.items():
                    row.setdefault(k, v)
        null_fields_json = d.get("null_fields_json")
        if null_fields_json:
            try:
                null_fields = json.loads(null_fields_json)
            except (json.JSONDecodeError, TypeError):
                null_fields = None
            if isinstance(null_fields, list):
                for k in null_fields:
                    if isinstance(k, str):
                        row[k] = None
        if d.get("generation") is not None:
            row["generation"] = d["generation"]
        return row

    def _row_to_session(self, d: dict[str, Any]) -> dict[str, Any]:
        session = self._row_to_metadata(d, include_computed=False)
        scenes_json = d.get("anchor_activity_scenes_json")
        if scenes_json is not None:
            session["anchor_activity_scenes"] = json.loads(scenes_json)
        return session
